version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back
    ports:
      - 3307:3306 # default port 3306
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin # https://github.com/phpmyadmin/docker
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db #define address/host name of the MySQL server
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back
networks:
  back:
volumes:
  db_data:
